name = "DerivativeFreeSolvers"
uuid = "704b706e-a0d9-11e9-03cb-eb2963733e22"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"

[compat]
NLPModels = "0.14"
SolverCore = "0.1"
julia = "1"

[extras]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ADNLPModels", "Logging", "Test"]
